# Generated by Django 4.1.7 on 2023-03-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='TestData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('revenue', models.CharField(max_length=255)),
                ('profit', models.CharField(max_length=255)),
                ('roi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestData3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('revenue', models.CharField(max_length=255)),
                ('profit', models.CharField(max_length=255)),
                ('roi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestData4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('revenue', models.CharField(max_length=255)),
                ('profit', models.CharField(max_length=255)),
                ('roi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestData5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('revenue', models.CharField(max_length=255)),
                ('profit', models.CharField(max_length=255)),
                ('roi', models.CharField(max_length=255)),
            ],
        ),
    ]
